name: Deploy Java App to GCloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPO/your-app:latest .
          docker push us-central1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPO/your-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-app \
            --image us-central1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPO/your-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
